// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEG2dFNTVyA34xzwLCrVAZkK47n3Q6XMY',
    appId: '1:588203814855:android:7830faef3c7c7b466a73e2',
    messagingSenderId: '588203814855',
    projectId: 'connect-me-e20b1',
    storageBucket: 'connect-me-e20b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXrAksodD_jnFLuyoF0sDiGpS4i3b4mYE',
    appId: '1:588203814855:ios:9d121a9af9dac9406a73e2',
    messagingSenderId: '588203814855',
    projectId: 'connect-me-e20b1',
    storageBucket: 'connect-me-e20b1.firebasestorage.app',
    iosBundleId: 'com.connectme.connectMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXrAksodD_jnFLuyoF0sDiGpS4i3b4mYE',
    appId: '1:588203814855:ios:9d121a9af9dac9406a73e2',
    messagingSenderId: '588203814855',
    projectId: 'connect-me-e20b1',
    storageBucket: 'connect-me-e20b1.firebasestorage.app',
    iosBundleId: 'com.connectme.connectMe',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnTzq_7egwxvpda85PdMMee48go75cdv8',
    appId: '1:588203814855:web:d380c2746782fe8a6a73e2',
    messagingSenderId: '588203814855',
    projectId: 'connect-me-e20b1',
    authDomain: 'connect-me-e20b1.firebaseapp.com',
    storageBucket: 'connect-me-e20b1.firebasestorage.app',
  );

}